In [1]:
import pandas as pd

In [3]:
# load dataset
porto_df = pd.read_csv("porto/porto.csv")

In [4]:
display(porto_df)

,TRIP_ID,CALL_TYPE,ORIGIN_CALL,ORIGIN_STAND,TAXI_ID,TIMESTAMP,DAY_TYPE,MISSING_DATA,POLYLINE
0,1372636858620000589,C,NaN,NaN,20000589,1372636858,A,False,"[[-8.618643,41.141412],[-8.618499,41.141376],[..."
1,1372637303620000596,B,NaN,7.0,20000596,1372637303,A,False,"[[-8.639847,41.159826],[-8.640351,41.159871],[..."
2,1372636951620000320,C,NaN,NaN,20000320,1372636951,A,False,"[[-8.612964,41.140359],[-8.613378,41.14035],[-..."
3,1372636854620000520,C,NaN,NaN,20000520,1372636854,A,False,"[[-8.574678,41.151951],[-8.574705,41.151942],[..."
4,1372637091620000337,C,NaN,NaN,20000337,1372637091,A,False,"[[-8.645994,41.18049],[-8.645949,41.180517],[-..."
...,...,...,...,...,...,...,...,...,...
1710665,1404171463620000698,C,NaN,NaN,20000698,1404171463,A,False,"[[-8.612469,41.14602],[-8.612487,41.145993],[-..."
1710666,1404171367620000670,C,NaN,NaN,20000670,1404171367,A,False,"[[-8.610138,41.140845],[-8.610174,41.140935],[..."
1710667,1388745716620000264,C,NaN,NaN,20000264,1388745716,A,False,[]
1710668,1404141826620000248,B,NaN,12.0,20000248,1404141826,A,False,"[[-8.630712,41.154885],[-8.63073,41.154813],[-..."
1710669,1404157147620000079,B,NaN,34.0,20000079,1404157147,A,False,"[[-8.615538,41.140629],[-8.615421,41.140746],[..."

## Part 1 - EDA
### Examine main attributes, get an overview of the data distribution and investigate the presence and impact of missing trajectories

#### TRIP_ID inspection

In [24]:
# check whether TRIP_ID is unique for each row
print("Number of unique TRIP_IDs:", len(porto_df["TRIP_ID"].unique()))
print("Number of rows in the dataset:", len(porto_df["TRIP_ID"]))
print("Number of duplicated TRIP_IDs:",  len(porto_df["TRIP_ID"]) - len(porto_df["TRIP_ID"].unique()))

# check how many rows are duplicated for each TRIP_ID and inspect trips with the most rows (value_counts sorts by TRIP_ID)
print("")
print("Number of duplicated rows for each TRIP_ID and inspection of the trip with the highest count:")
duplicate_ids = porto_df[porto_df["TRIP_ID"].duplicated(keep=False)].sort_values(by=["TRIP_ID"])
display(duplicate_ids.value_counts("TRIP_ID").head())
display(duplicate_ids[duplicate_ids["TRIP_ID"] == 1397172149620000454 ])

# inspect the first 10 rows of the duplicated trips
print("First 10 rows of duplicated trips:")
display(duplicate_ids.head(10))

Number of unique TRIP_IDs: 1710589
Number of rows in the dataset: 1710670
Number of duplicated TRIP_IDs: 81

Number of duplicated rows for each TRIP_ID and inspection of the trip with the highest count:

TRIP_ID
1397172149620000454    3
1372702836620000080    2
1373210896620000598    2
1373025987620000601    2
1374014097620000337    2
Name: count, dtype: int64

,TRIP_ID,CALL_TYPE,ORIGIN_CALL,ORIGIN_STAND,TAXI_ID,TIMESTAMP,DAY_TYPE,MISSING_DATA,POLYLINE
1304113,1397172149620000454,A,30929.0,NaN,20000454,1397172149,A,False,"[[-8.618391,41.162067],[-8.6184,41.161446],[-8..."
1304114,1397172149620000454,C,NaN,NaN,20000454,1397172149,A,False,"[[-8.618391,41.162067],[-8.6184,41.161446],[-8..."
1304115,1397172149620000454,C,NaN,NaN,20000454,1397172149,A,False,"[[-8.618391,41.162067],[-8.6184,41.161446],[-8..."

First 10 rows of duplicated trips:

,TRIP_ID,CALL_TYPE,ORIGIN_CALL,ORIGIN_STAND,TAXI_ID,TIMESTAMP,DAY_TYPE,MISSING_DATA,POLYLINE
3519,1372702836620000080,B,NaN,16.0,20000080,1372702836,A,False,"[[-8.635275,41.193729],[-8.634519,41.192901]]"
3720,1372702836620000080,C,NaN,NaN,20000080,1372702836,A,False,"[[-8.62776,41.17554],[-8.62776,41.17554],[-8.6..."
21282,1373025987620000601,A,2002.0,NaN,20000601,1373025987,A,False,[]
21385,1373025987620000601,C,NaN,NaN,20000601,1373025987,A,False,"[[-8.604108,41.182569],[-8.604072,41.182605],[..."
33228,1373210896620000598,B,NaN,57.0,20000598,1373210896,A,False,"[[-8.610885,41.145525]]"
33350,1373210896620000598,C,NaN,NaN,20000598,1373210896,A,False,"[[-8.610813,41.14548],[-8.610732,41.145579],[-..."
51623,1373551710620000014,B,NaN,49.0,20000014,1373551710,A,False,"[[-8.587278,41.147325],[-8.587278,41.147325]]"
51966,1373551710620000014,C,NaN,NaN,20000014,1373551710,A,False,"[[-8.602938,41.179716],[-8.603937,41.179932],[..."
76527,1374014097620000337,C,NaN,NaN,20000337,1374014097,A,False,"[[-8.648451,41.164785]]"
76596,1374014097620000337,C,NaN,NaN,20000337,1374014097,A,False,"[[-8.648478,41.164758],[-8.648478,41.164758],[..."

It appears that 81 trips have does not have unique TRIP_IDs and that the rows with similar TRIP_ID are not simply duplicates of one another. It appears that for most cases there are two duplicate rows, but there is one case where there are three duplicate rows. For the duplicated rows TAXI_ID and timestamp appear to be the same. This could indicate that the first initiaton of saving the trip failed and therefore the the second or third is an attempt to correct the error. For example some of the first TRIP_IDs initiated have were few coordinates in the POLYLINE field. Since we cannot verify whether our hypothesis is correct, we have decisded to remove the IDs with multiple rows.

#### CALL_TYPE, ORIGIN_CALL and ORIGIN_STAND inspection

In [ ]:
# check that there are in fact only A, B and C values for calltype
display(porto_df["CALL_TYPE"].unique())

# Check that all rows with CALL_TYPE=A has a value for ORIGIN_CALL and visa versa



# check that

array(['C', 'B', 'A'], dtype=object)

CALL_TYPE only contains the values A, B, C as expected.

In [ ]:
# Unique identifies for each trip
display(porto_df["TRIP_ID"].unique())

# Code indicating how the trip was initiated. A = Trip dispatched from the central, B = Trip requested directly form a taxi stand, C = Trip hailed randomly in the street
display(porto_df["CALL_TYPE"].unique())

# ID of the client who intiated the call (only set when CALLTYPE = A) Otherwise null
display(porto_df["ORIGIN_CALL"].unique())

# Taxi stand ID where the trip started (only set when CALLTYPE = B) Otherwise null
display(porto_df["ORIGIN_STAND"].unique())

# Unique identifies for each taxi
display(porto_df["TAXI_ID"].unique())

# Start time of the trip, expressed as Unix time (seconds since 1970-01-01). Should be converted to a standard DATETIME format for queries.
display(porto_df["TIMESTAMP"].unique())

# Indicates whether the trip occurred on a normal day, a holiday, or the day before a holiday. A: Normal day (workday or weekend), B: Holiday or special day, C: Day before a holiday.
display(porto_df["DAY_TYPE"].unique())

# Boolean flag indicating whether there are missing GPS points in the POLYLINE. FALSE means the data is complete, TRUE means some points
display(porto_df["MISSING_DATA"].unique())

# POLYLINE: A list of GPS points forming the trajectory. Each point is represented as [longitude, latitude], sampled at 15-second intervals.
porto_df["POLYLINE"].unique()

array([1372636858620000589, 1372637303620000596, 1372636951620000320, ...,
       1388745716620000264, 1404141826620000248, 1404157147620000079],
      shape=(1710589,))

array(['C', 'B', 'A'], dtype=object)

array([   nan, 31508., 33180., ..., 47501.,  4874., 34164.],
      shape=(57106,))

array([nan,  7., 13., 28., 38., 52., 23., 22., 57., 34., 15., 18., 47.,
        9., 30., 51., 60., 12., 58., 25., 14., 33., 61., 53., 36., 20.,
       56., 42., 24.,  6., 35., 26., 27.,  1., 21., 11.,  8., 55.,  3.,
       16., 17., 40., 32., 59., 63., 62., 45., 54., 29., 10., 49., 37.,
       19., 31., 39.,  2., 44., 50., 43., 46., 41.,  5.,  4., 48.])

array([20000589, 20000596, 20000320, 20000520, 20000337, 20000231,
       20000456, 20000011, 20000403, 20000233, 20000571, 20000497,
       20000570, 20000005, 20000089, 20000423, 20000657, 20000309,
       20000161, 20000178, 20000235, 20000653, 20000009, 20000648,
       20000424, 20000010, 20000372, 20000686, 20000435, 20000154,
       20000060, 20000167, 20000503, 20000621, 20000463, 20000612,
       20000360, 20000574, 20000173, 20000560, 20000492, 20000112,
       20000305, 20000004, 20000620, 20000671, 20000341, 20000015,
       20000307, 20000171, 20000201, 20000007, 20000199, 20000611,
       20000398, 20000067, 20000569, 20000473, 20000367, 20000672,
       20000190, 20000600, 20000496, 20000013, 20000454, 20000534,
       20000195, 20000406, 20000325, 20000101, 20000632, 20000308,
       20000333, 20000481, 20000486, 20000450, 20000545, 20000665,
       20000012, 20000688, 20000540, 20000436, 20000517, 20000153,
       20000458, 20000577, 20000105, 20000128, 20000616, 20000477,
       20000197, 20000476, 20000480, 20000451, 20000663, 20000386,
       20000561, 20000472, 20000280, 20000565, 20000432, 20000329,
       20000073, 20000397, 20000285, 20000286, 20000024, 20000239,
       20000578, 20000514, 20000152, 20000515, 20000247, 20000344,
       20000184, 20000502, 20000400, 20000256, 20000625, 20000196,
       20000331, 20000678, 20000901, 20000421, 20000229, 20000381,
       20000086, 20000539, 20000242, 20000662, 20000279, 20000076,
       20000351, 20000529, 20000042, 20000408, 20000674, 20000304,
       20000071, 20000038, 20000137, 20000618, 20000179, 20000120,
       20000166, 20000151, 20000434, 20000549, 20000484, 20000075,
       20000542, 20000391, 20000131, 20000346, 20000296, 20000058,
       20000429, 20000268, 20000051, 20000623, 20000021, 20000046,
       20000359, 20000470, 20000114, 20000188, 20000026, 20000077,
       20000499, 20000180, 20000409, 20000562, 20000651, 20000669,
       20000607, 20000049, 20000272, 20000189, 20000455, 20000144,
       20000100, 20000576, 20000554, 20000281, 20000068, 20000050,
       20000039, 20000186, 20000687, 20000104, 20000460, 20000446,
       20000174, 20000255, 20000065, 20000257, 20000192, 20000507,
       20000617, 20000664, 20000027, 20000267, 20000319, 20000380,
       20000251, 20000163, 20000682, 20000361, 20000138, 20000495,
       20000207, 20000349, 20000684, 20000525, 20000045, 20000633,
       20000269, 20000640, 20000258, 20000142, 20000680, 20000116,
       20000001, 20000254, 20000384, 20000377, 20000626, 20000294,
       20000692, 20000030, 20000579, 20000249, 20000440, 20000271,
       20000057, 20000675, 20000588, 20000363, 20000099, 20000326,
       20000148, 20000546, 20000230, 20000113, 20000557, 20000376,
       20000126, 20000006, 20000288, 20000311, 20000598, 20000352,
       20000111, 20000222, 20000085, 20000518, 20000443, 20000330,
       20000508, 20000226, 20000370, 20000602, 20000387, 20000353,
       20000129, 20000524, 20000048, 20000649, 20000468, 20000467,
       20000245, 20000123, 20000601, 20000093, 20000031, 20000487,
       20000261, 20000676, 20000431, 20000605, 20000107, 20000047,
       20000215, 20000159, 20000156, 20000338, 20000289, 20000410,
       20000198, 20000685, 20000074, 20000516, 20000453, 20000604,
       20000345, 20000697, 20000315, 20000541, 20000158, 20000136,
       20000693, 20000094, 20000014, 20000022, 20000535, 20000054,
       20000108, 20000118, 20000328, 20000608, 20000140, 20000395,
       20000083, 20000018, 20000494, 20000619, 20000594, 20000246,
       20000177, 20000040, 20000217, 20000388, 20000615, 20000595,
       20000464, 20000206, 20000092, 20000321, 20000053, 20000356,
       20000216, 20000667, 20000681, 20000036, 20000017, 20000310,
       20000303, 20000146, 20000430, 20000668, 20000324, 20000488,
       20000109, 20000297, 20000521, 20000314, 20000658, 20000172,
       20000392, 20000347, 20000504, 20000055, 20000465, 20000448,
       20000295, 20000452, 20000634, 20000547, 20000080, 20000903,
       20000008, 20000603, 20000041, 20000252, 20000327, 20000513,
       20000095, 20000081, 20000509, 20000343, 20000032, 20000523,
       20000066, 20000419, 20000426, 20000044, 20000483, 20000243,
       20000586, 20000527, 20000624, 20000342, 20000273, 20000981,
       20000900, 20000334, 20000904, 20000548, 20000482, 20000157,
       20000037, 20000276, 20000572, 20000160, 20000373, 20000084,
       20000119, 20000098, 20000695, 20000224, 20000902, 20000225,
       20000250, 20000023, 20000597, 20000606, 20000263, 20000941,
       20000610, 20000591, 20000506, 20000072, 20000543, 20000383,
       20000020, 20000449, 20000260, 20000003, 20000364, 20000393,
       20000002, 20000187, 20000205, 20000312, 20000510, 20000389,
       20000340, 20000500, 20000407, 20000980, 20000213, 20000969,
       20000609, 20000332, 20000121, 20000362, 20000170, 20000585,
       20000185, 20000264, 20000698, 20000670, 20000911, 20000248,
       20000079, 20000940, 20000970, 20000931])

array([1372636858, 1372637303, 1372636951, ..., 1404171367, 1388745716,
       1404157147], shape=(1655366,))

array(['A'], dtype=object)

array([False,  True])

array(['[[-8.618643,41.141412],[-8.618499,41.141376],[-8.620326,41.14251],[-8.622153,41.143815],[-8.623953,41.144373],[-8.62668,41.144778],[-8.627373,41.144697],[-8.630226,41.14521],[-8.632746,41.14692],[-8.631738,41.148225],[-8.629938,41.150385],[-8.62911,41.151213],[-8.629128,41.15124],[-8.628786,41.152203],[-8.628687,41.152374],[-8.628759,41.152518],[-8.630838,41.15268],[-8.632323,41.153022],[-8.631144,41.154489],[-8.630829,41.154507],[-8.630829,41.154516],[-8.630829,41.154498],[-8.630838,41.154489]]',
       '[[-8.639847,41.159826],[-8.640351,41.159871],[-8.642196,41.160114],[-8.644455,41.160492],[-8.646921,41.160951],[-8.649999,41.161491],[-8.653167,41.162031],[-8.656434,41.16258],[-8.660178,41.163192],[-8.663112,41.163687],[-8.666235,41.1642],[-8.669169,41.164704],[-8.670852,41.165136],[-8.670942,41.166576],[-8.66961,41.167962],[-8.668098,41.168988],[-8.66664,41.170005],[-8.665767,41.170635],[-8.66574,41.170671]]',
       '[[-8.612964,41.140359],[-8.613378,41.14035],[-8.614215,41.140278],[-8.614773,41.140368],[-8.615907,41.140449],[-8.616609,41.140602],[-8.618472,41.141412],[-8.620623,41.142789],[-8.622558,41.144094],[-8.62506,41.144805],[-8.627436,41.144733],[-8.630082,41.145174],[-8.6319,41.146461],[-8.632584,41.147316],[-8.631252,41.148774],[-8.629713,41.150628],[-8.628804,41.152077],[-8.628579,41.152464],[-8.62875,41.152662],[-8.630424,41.15277],[-8.632683,41.152779],[-8.635131,41.152563],[-8.637705,41.153013],[-8.64036,41.15358],[-8.642205,41.154021],[-8.644068,41.154507],[-8.646453,41.154336],[-8.648613,41.1543],[-8.649504,41.154336],[-8.649837,41.154354],[-8.649837,41.1543],[-8.649882,41.154282],[-8.649936,41.1543],[-8.6499,41.154264],[-8.599383,41.141736],[-8.59653,41.140566],[-8.65008,41.154291],[-8.650395,41.153814],[-8.650377,41.153832],[-8.650359,41.153787],[-8.649891,41.153166],[-8.649369,41.152572],[-8.649198,41.152374],[-8.649711,41.151213],[-8.649117,41.150466],[-8.649117,41.149062],[-8.648613,41.148261],[-8.648424,41.148225],[-8.647587,41.148405],[-8.64594,41.148414],[-8.643861,41.148135],[-8.642763,41.148027],[-8.640918,41.14836],[-8.637759,41.148351],[-8.635338,41.147964],[-8.633277,41.147172],[-8.631513,41.146146],[-8.629776,41.14503],[-8.627814,41.144643],[-8.625996,41.144769],[-8.624088,41.144463],[-8.621325,41.143401],[-8.619444,41.141961],[-8.617365,41.140863],[-8.61597,41.14053]]',
       ...,
       '[[-8.610138,41.140845],[-8.610174,41.140935],[-8.613126,41.141583],[-8.614341,41.141169],[-8.614386,41.142042],[-8.613927,41.142933],[-8.612883,41.143725],[-8.611911,41.144454],[-8.611326,41.144868],[-8.61084,41.14566],[-8.610147,41.146398],[-8.608968,41.146857],[-8.609553,41.147514],[-8.610651,41.147721],[-8.611065,41.147829],[-8.613108,41.148234],[-8.622468,41.14773],[-8.624817,41.148477],[-8.625771,41.149989],[-8.626014,41.15205],[-8.626689,41.154282],[-8.627814,41.156136],[-8.628444,41.156892],[-8.627976,41.157594],[-8.627931,41.158296],[-8.627418,41.158647],[-8.627436,41.158737],[-8.627436,41.158764],[-8.627427,41.158746],[-8.627454,41.158755]]',
       '[[-8.630712,41.154885],[-8.63073,41.154813],[-8.630748,41.154795],[-8.630766,41.154768],[-8.630739,41.154507],[-8.630496,41.153589],[-8.628939,41.153634],[-8.628768,41.15439],[-8.627517,41.154651],[-8.627148,41.154651],[-8.627058,41.154624],[-8.627031,41.154624],[-8.626797,41.154651],[-8.626761,41.155065],[-8.625726,41.155461],[-8.624898,41.155623],[-8.624214,41.155911],[-8.623926,41.156856],[-8.623854,41.157045],[-8.623449,41.158314],[-8.6238,41.158863],[-8.623413,41.159313],[-8.622594,41.160132],[-8.622207,41.160384],[-8.621109,41.160501],[-8.620803,41.161392],[-8.619147,41.162265],[-8.617356,41.162472],[-8.614854,41.162202],[-8.614512,41.162094],[-8.614476,41.162175],[-8.614476,41.162184],[-8.613819,41.161986],[-8.612865,41.161959],[-8.61273,41.161932],[-8.611281,41.161887],[-8.611173,41.162472],[-8.611056,41.163093],[-8.611038,41.164236],[-8.609985,41.164578],[-8.609265,41.164533],[-8.607501,41.164479],[-8.606421,41.164479],[-8.606349,41.165253],[-8.606358,41.165235],[-8.606376,41.165244],[-8.606088,41.165424],[-8.60409,41.165514],[-8.602425,41.165712],[-8.601777,41.166657],[-8.601084,41.167116],[-8.598663,41.167098],[-8.597421,41.166684],[-8.597421,41.166117],[-8.595702,41.166693],[-8.594055,41.167125],[-8.593317,41.167512],[-8.591436,41.168547],[-8.589609,41.169636],[-8.588628,41.17077],[-8.587791,41.172138],[-8.587026,41.173524]]',
       '[[-8.615538,41.140629],[-8.615421,41.140746],[-8.614791,41.140953],[-8.614503,41.141331],[-8.61444,41.141808],[-8.614008,41.142924],[-8.612505,41.143851],[-8.611659,41.144526],[-8.611209,41.144886],[-8.611209,41.144886],[-8.61111,41.144886],[-8.61111,41.144886],[-8.610705,41.145831],[-8.609535,41.146677],[-8.608752,41.147217],[-8.609751,41.14764],[-8.610714,41.147847],[-8.610714,41.147847],[-8.611074,41.147802],[-8.61273,41.148099],[-8.620254,41.147649],[-8.620758,41.149089],[-8.620929,41.149854],[-8.620893,41.149881],[-8.620893,41.149881],[-8.620893,41.149881],[-8.620893,41.149881]]'],
      shape=(1703650,), dtype=object)